### ISSUE TITLE
simultaneously evaluated objective and constraint

### ISSUE THREAD

**Issue by tpapp** [JuliaSmoothOptimizers/Percival.jl#51]
Thanks for this great package, I find it very useful for structural estimation in macroeconomics.

A lot of problems I work with calculate the objective and the constraint simultaneously. Eg (stylized)

1. given a set of structural parameters `θ` and prices `p`, 
2. agents solve their optimization problem to obtain an policy `k = f(θ, p)`,
3. mass distributions `d = g(θ, p, k)` are calculated, *which is the most costly step*, `d` is large
4. the objective is a moment distance `m(θ, p, d)`, while the constraint (market clearing) is `c(θ, p, d) = 0`.

Eg typically `θ` and `p` have a few ten-hundred elements, `d` thousands or millions.

Currently the way `NLPModel` and `ADNLPModel` are set up, `f` and `g` is evaluated *twice*. My understanding of augmented Lagrangian methods suggest that for an inner objective, they objective and the constrained are combined, so a function that returns both in a single pass could be used.

Sorry if this can be done in an obvious way with the current setup already, I could not figure it out.

**Comment by dpo** [comment]
The NLPModels API makes provisions for an `objcons()` method but it isn’t used in the current implementation of Percival. We’ll have to think how to work it in.

Sorry if this isn’t a permanent solution but for the time being, perhaps a simple caching mechanism could save you some computations?!

**Comment by tpapp** [comment]
Where is `objcons` documented?

**Comment by tmigot** [comment]
Hi @tpapp 
`objcons` as well as all the functions used to access the NLPModel in general, are defined in `NLPModels.jl`. So, you can do:
```
using NLPModels
? objcons
```
or visit directly [NLPModels.jl's doc](https://juliasmoothoptimizers.github.io/NLPModels.jl/dev/api/)
